routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'IndexController@index')->name('index');

Route::post('/tournaments/generate', 'ResultsController@generateResults')->name('tournaments.generate-results');
Route::post('/tournaments/generate-eliminations', 'ResultsController@generateEliminationTable')->name('tournaments.generate-eliminations');

app/Models/Game.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\{Builder, Model, Relations\HasMany};
use Illuminate\Support\Facades\DB;

/**
 * @property int $id
 * @property int $first_team
 * @property int $second_team
 * @property int $first_team_score
 * @property int $second_team_score
 * @property int $winner_id
 * @method static Builder|Game newModelQuery()
 * @method static Builder|Game newQuery()
 * @method static Builder|Game query()
 * @method static Builder|Game whereFirstTeam($value)
 * @method static Builder|Game whereFirstTeamScore($value)
 * @method static Builder|Game whereId($value)
 * @method static Builder|Game whereSecondTeam($value)
 * @method static Builder|Game whereSecondTeamScore($value)
 * @method static Builder|Game whereWinnerId($value)
 */
class Game extends Model
{
    public $timestamps = false;

    protected $table = 'games';
    protected $fillable = ['first_team', 'second_team', 'first_team_score', 'second_team_score', 'winner_id'];

    /**
     * @param array $results
     * @param int   $leagueId
     * @return void
     */
    public static function saveResults(array $results, int $leagueId): void
    {
        DB::transaction(static function () use ($results, $leagueId) {
            League::find($leagueId)->games()->delete();
            self::insert($results);
        });
    }

    /**
     * @return HasMany
     */
    public function winner(): HasMany
    {
        return $this->hasMany(Team::class, 'id', 'winner_id');
    }

    /**
     * @return HasMany
     */
    public function firstTeam(): HasMany
    {
        return $this->belongsTo(Team::class, 'id', 'first_team');
    }

    /**
     * @return HasMany
     */
    public function secondTeam(): HasMany
    {
        return $this->belongsTo(Team::class, 'id', 'second_team');
    }

    /**
     * @return string
     */
    public function getResultAttribute(): string
    {
        return $this->first_team_score . ' : ' . $this->second_team_score;
    }
}

resources/views/index/partials/results-table.blade.php
@foreach($league->teams as $team)

    @if ($loop->first)
        <tr>
            <td>Teams</td>
            @foreach($league->teams as $leagueTeam)
                <td> {{ $leagueTeam->name }} </td>
            @endforeach
            <td>Score</td>
        </tr>
    @endif

    <tr>
        <td> {{ $team->name }} </td>

        @forelse($team->games as $game)
            @if($game->first_team_score === null || $game->second_team_score === null)
                <td class="empty-cell"></td>
            @else
                <td class="results-cell">{{ $game->result }}</td>
            @endif
        @empty
            @for($counter = 0; $counter <= \App\Models\League::TEAMS_PER_LEAGUE; $counter++)
                <td class="results-cell"></td>
            @endfor
        @endforelse
        <td>{{ $team->score === 0 ? '-' : $team->score }}</td>
    </tr>

@endforeach

resources/views/index/partials/tournament-brackets.blade.php
<div class="tournament">
    <div>
        @foreach($eliminations->take(4) as $elimination)
            <div>
                <ul>
                    <li class="winner">{{ $elimination->winner->name }}</li>
                    <li>{{ $elimination->loser->name }}</li>
                </ul>
            </div>
        @endforeach
    </div>
    <div>
        @foreach($eliminations->splice(4,2) as $elimination)
            <div>
                <ul>
                    <li class="winner">{{ $elimination->winner->name }}</li>
                    <li>{{ $elimination->loser->name }}</li>
                </ul>
            </div>
        @endforeach
    </div>
    <div>
        <div>
            <ul>
                <li class="winner">{{ $eliminations->last()->winner->name }}</li>
                <li>{{ $eliminations->last()->loser->name }}</li>
            </ul>
        </div>
    </div>
    <div>
        <div>
            <ul>
                <li class="winner">{{ $eliminations->last()->winner->name }}</li>
            </ul>
        </div>
    </div>
</div>